name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Lint JavaScript
        run: |
          echo "Running ESLint (simplified for demo)..."
          if grep -q "console.log" script.js; then
            echo "Warning: console.log statements found in script.js"
            # In a real project, we'd fail here
            # exit 1
          else
            echo "No linting issues found"
          fi

      - name: Run tests
        run: node test.js

  deploy:
    needs: lint-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
